//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Crime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Crime()
        {
            this.Evidences = new HashSet<Evidence>();
            this.SuspectCrimes = new HashSet<SuspectCrime>();
            this.TaskForces = new HashSet<TaskForce>();
        }
    
        public int CrimeId { get; set; }
        public int CaseId { get; set; }
        public System.DateTime TimeDate { get; set; }
        public string Location { get; set; }
        public string CrimeType { get; set; }
        public int Severity { get; set; }
    
        public virtual Investigation Investigation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Evidence> Evidences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuspectCrime> SuspectCrimes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskForce> TaskForces { get; set; }
    }
}
