//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evidence
    {
        public int EvidenceId { get; set; }
        public int CrimeId { get; set; }
        public System.DateTime DateFound { get; set; }
        public string Description { get; set; }
        public decimal EvidenceWeight { get; set; }
    
        public virtual Crime Crime { get; set; }
    }
}
