//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class PoliceDivision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PoliceDivision()
        {
            this.Officers = new HashSet<Officer>();
        }
    
        public int DivisionId { get; set; }
        public string Location { get; set; }
        public Nullable<int> PoliceChiefId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Officer> Officers { get; set; }
        public virtual Officer Officer { get; set; }
    }
}
