//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suspect
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Suspect()
        {
            this.SuspectCrimes = new HashSet<SuspectCrime>();
        }
    
        public int SuspectId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Mugshot { get; set; }
        public string DNA { get; set; }
        public string Race { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<int> Weight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuspectCrime> SuspectCrimes { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
